title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-slatetitle: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-slate
