# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "mint"

# Site Settings
locale                   : "en-US"
title                    : ""
title_separator          : "-"
subtitle                 : ""
name                     : "team-juniper"
description              : "Capstone 2024"
url                      : "https://janhavi-ucb.github.io"
baseurl                  : "/juniper.github.io/"
repository               : "https://github.com/janhavi-ucb/juniper.github.io"
teaser                   : "images/bg_img.png"
logo                     : "images/JuniperLogo_Transparent.PNG"
masthead_title           : "JUNIPER: Privacy Interface for Large Language Model Interaction
  

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
